### ISSUE TITLE
fastMNN not finishing

### ISSUE THREAD

**Issue by rjb67** [LTLA/batchelor#3] opened 2019-05-30 13:33 UTC
I am testing fastMNN() on our single-cell dataset to see how well it works at removing batch effects in our dataset. I got matrices from the groups I wanted to test using by extracting the specific cells by their batches from a Seurat object, making sure they were in the right sparse matrix format. I then ran it overnight, setting it to run with multiple cores.

However, it did not appear to work as it was still processing and did not appear to be using the multiple cores like I input. I used the same method of selecting multiple cores as I did with a previous runthrough of scran so I don't think it should have been that. I have also run Seurat CCA overnight on a less powerful computer and have been able to get results so I don't think processing power is the issue.

What could have gone wrong that it wasn't able to complete processing? Or is it actually that intensive of a function that it would require more than a day to finish running?

**Comment by LTLA** [comment] 2019-05-31 02:27
You should really put in your call to `fastMNN()`. Without this (and session information), I can only guess.

So, if I had to guess, I would say that you haven't set `BSPARAM=IrlbaParam(deferred=TRUE)` as instructed [here](https://bioconductor.org/packages/release/workflows/vignettes/simpleSingleCell/inst/doc/batch.html). This means that the algorithm defaults to an exact PCA, which is slow for many cells.

You could argue that the default should be `IrlbaParam()` anyway, and I would be inclined to agree - the current defaults are inherited from _scran_, which favors accuracy and stability over speed by default. But perhaps we could make an exception for methods that are explicitly named `fast`, `quick`, etc.

**Comment by LTLA** [comment] 2019-06-18 07:14
The defaults were changed to use `IrlbaParam(deferred=TRUE)`, which should make it easier for people. So I'm closing this unless the cause is something else.

**Closed as completed by LTLA** 2019-06-18 07:14 UTC
